dm_cartpole:
  task: swingup
  image_observation:
    enabled: true
    image_size: [64, 64]
    image_format: "channels_first"
    visualize_reward: true
  cost_multiplier: 0.2
  slider_position_bound: 0.5
